--HSQLDB

--drop schema if exists wt_tables cascade;

--create schema wt_tables;
--authorization wt;
--comment on schema wt_tables
--is 'wt_tables';

drop table if exists access_control_item cascade;

--create sequence access_control_item_sequ start with 1 increment by 1;
create table if not exists access_control_item
  (
    id             bigint generated by default as identity primary key ,
    sys_name       varchar (30) ,
    name           varchar (100) ,
    is_deleted     char(1) default 'N' not null check(is_deleted = 'Y' or is_deleted = 'N') ,
    display_order  numeric(100) ,
    search_synonim varchar (100)
  ) ;


comment on table access_control_item
IS
  'Справочник объектов прав' ;

commit

insert into access_control_item (
        sys_name, name, is_deleted, display_order, search_synonim
    ) values (
        'admin', 'admin', 'N', 1, 'admin'
    )
    ;
insert into access_control_item (
        sys_name, name, is_deleted, display_order, search_synonim
    ) values (
        'admin2', 'admin2', 'N', 1, 'admin2'
    )
    ;
